stages:
  - build
  - docker

build:
  stage: build
  image: gradle:8.10.2-jdk17
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar # 빌드 후 .jar 파일을 아티팩트로 저장

docker_build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin # Docker Hub 로그인
  script:
    - echo "Building the Docker image..."
    - docker build -t $DOCKER_IMAGE:$TAG .
    - docker push $DOCKER_IMAGE:$TAG # 빌드한 이미지를 Docker Hub에 푸시
