image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE: "veronica2550/ormee-server"
  TAG: "latest"

stages:
  - build

build:
  stage: build
  script:
    - echo "Building the Docker image..."
    - docker build -t $DOCKER_IMAGE:$TAG .
  only:
    - main  # 빌드할 브랜치
