stages:
  - build
  - docker

build:
  stage: build
  image: gradle:7.6-jdk17 # Gradle과 JDK 17이 포함된 이미지
  script:
    - gradle clean build # Gradle 빌드 수행
  artifacts:
    paths:
      - build/libs/*.jar # 빌드 후 .jar 파일을 아티팩트로 저장

docker_build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD # Docker Hub 로그인
  script:
    - echo "Building the Docker image..."
    - docker build -t $DOCKER_IMAGE:$TAG .
    - docker push $DOCKER_IMAGE:$TAG # 빌드한 이미지를 Docker Hub에 푸시
