workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      when: always
    - when: never

stages:
  - build
  - docker
  - deploy

variables:
  IMAGE_TAG: $CI_COMMIT_SHA
  DOCKER_IMAGE: ${DOCKER_USERNAME}/ormee-server

build:
  stage: build
  image: gradle:8.10.2-jdk17
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day

docker_build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - echo "$CI_DEPLOY_PASSWORD" | docker login $CI_REGISTRY -u $CI_DEPLOY_USER --password-stdin
    - docker build -t $DOCKER_IMAGE:$IMAGE_TAG .
    - docker push $DOCKER_IMAGE:$IMAGE_TAG
    - docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest

deploy_to_ec2:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -o StrictHostKeyChecking=no ec2-user@$EC2_HOST "
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD &&
        docker stop app_container || true &&
        docker rm app_container || true &&
        docker rmi $DOCKER_IMAGE:$IMAGE_TAG || true &&
        docker pull $DOCKER_IMAGE:$IMAGE_TAG &&
        docker run -d --name app_container -p 8080:8080 $DOCKER_IMAGE:$IMAGE_TAG"
        
      